[package]
name = "pyo3_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


crate-type = ["cylib"]

[dependencies]
pyo3 = {version="0.19.2",features=["auto-initialize"]}


